kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: database-provisioner-role
  labels:
    plural.sh/part-of: database-interface
    plural.sh/component: provisioner
    plural.sh/version: main
    plural.sh/name: database-interface-provisioner
rules:
  - apiGroups: ["database.plural.sh"]
    resources: ["buckets", "databaseaccess"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["database.plural.sh"]
    resources: ["databaseaccesses"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "delete", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: database-provisioner-role-binding
  labels:
    plural.sh/part-of: database-interface
    plural.sh/component: provisioner
    plural.sh/version: main
    plural.sh/name: database-interface-provisioner
subjects:
  - kind: ServiceAccount
    name: database-provisioner-sa
    namespace: default # must set to default. see https://github.com/kubernetes-sigs/kustomize/issues/1377#issuecomment-694731163
roleRef:
  kind: ClusterRole
  name: database-provisioner-role
  apiGroup: rbac.authorization.k8s.io