apiVersion: v1
kind: Secret
metadata:
  name: database-provisioner
  labels:
    plural.sh/part-of: database-interface
    plural.sh/component: provisioner
    plural.sh/version: main
    plural.sh/name: database-interface-provisioner
type: Opaque
stringData:
  DB_HOST: localhost
  DB_PASSWORD: postgres
  DB_PORT: 5432
  DB_USER: postgres